spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: bruce
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall,slf4j


      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false



      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false


#
#  redis:
#    host: r-bp1nc7reqesxisgxpipd.redis.rds.aliyuncs.com
#    port: 6379
#    password: lfy:Lfy123456
#    client-type: jedis
#    jedis:
#      pool:
#        max-active: 10
#        min-idle: 5

    #   or    client-type: lettuce
#    lettuce:
#      pool:
#        max-active: 10
#        min-idle: 5

#    jedis:
#      pool:
#


#   url: redis://lfy:Lfy123456@r-bp1nc7reqesxisgxpipd.redis.rds.aliyuncs.com:6379


    tomcat:
      max-active: 12
  jdbc:
    template:
      query-timeout: 3

# 配置mybatis 规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-location: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

# management 是所有actuator的配置
management:
  endpoints:
    enabled-by-default: true # 默认开启所有监控端点
    web:
      exposure:
        include: '*'  # 以web方式暴露所有端点
